apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw-node-secrets
  namespace: openclaw-node
spec:
  encryptedData:
    OPENCLAW_GATEWAY_TOKEN: AgBlnt9PJDvomPBrvblPL5X9/9nKmXe0dPfPul484NILKny47IZYFSY30857uZLG5dlG5eaRGOxjsoQacqH3f0C+OpUBtTARXI935iPJ4UniXJpfBGXQ6JyEgIysacEt3VqJ8tflFgVKsIrG3pgu3H3wfztDLpYN+1hals7EW2Gd1JH9hU1LUhYsEUdMTo3vDglNqTbOViHa6VHwxxGILSuKFh4GaUyp1NIwU99wnVZ+AvaQw0vtQJ/PBPALuw2rxNJarOr2W+NeLO5ge29cZR+9L+KuGK1JFZrHH+Z63bX2ZZySeZPnmZg9mtEYOgSst6II3LtqdToVqr3mKQTCO3Aaf7SPqFBlceDHW95lJiid7UMUEDOHhTT2SqeX9nz9V97NhsrbRtKgvsaBm6cyJicgi/35VogJW/2KSvaSuaBMyK20ZI0TSw5G+qq0FiYV+9QAkUf9Xw3SQjYyRbUvfzcntYZsr8y6Nqk3Km+nZUEMqi+Uqo9xK7TJGFmskU8KtSh7ayjiEfylBVeUxd9Rj1H/bmM8QiwifeyRpKcaRR6ODuhceAw6gZoHmdJ4BSX8FtPRypJOfgGB2rRQ4ISUcP7yspdGsXvGbcTKA+XVCtxDXuM17AzmUzvWJCGXz835auuPLHBKsDiACIfMh02Wuox1u8ZGCb+ZZM8thHRmPIo1aq5sRDbR2Zj4mbiRADiUFuHconHEOuBzBFkkTpGP/lW9aPph73gXebmpxTmAA//aMk/p33jbzr/8J9uyjWDaknc=
    TS_AUTHKEY: AgBLOv9VPPNcAPuo/hG9ThUkA1XgG4Y6YOn4pUzjxevdG+oJ1uP26eLKe52PVzPrvuOdk8UM9aAbDtNNykZ7/bhGKfrG/qQKP0jzOcP0XCMFhaxLNTYsmMiwCB7eCa99yEAgk+wT//wntrsWuiNv18fhNcxkqIBBsSeJKlXFlMHn49Xyj4SzL0UfbtIMv0OZvAYYmshDHAG8z/WrMqTN8La1xRIsg3hHyoyFaTh6FMISyiIZRJREr54vN8SivlhdbuSBRQeXK7JKOPJ4oiT8ZGjEyVF9QCiA1P+0ydQXBircqVE6AqXlGXhXxBulEQZa6gZF/xevuq+pe/2wn/6lh0udb6mpfT+BBJkEs7zCk5+gEWzCjQsk0f62j8tXrUEiNAeEJTSVSdBU3ubbKWA+hg0JKM/S4mWDaFUt7yk4aV1f86Ck31HofZJn9GssB87uoSx6Hq/NelNQKNujvdFBZW7X6MI0WRpfglxRKsrwMPSoMsR3s+JwOZI4tDEAouju6WfY9oVVIpEZQZFYiuAbimmswDNdrJTpwqt4RcRz2cDb3ULPcbP0J9zfM1gznIR/HCSf7Ksxg+DRxHQYPH80nxogJwPYMCpP68DvWaBNDz4tppugTScjObwAV+R7K1ejnxfyF5if/asfwLKpNOvBicRT1Rt7S/JJa9wtgi94UY+lrAOgOqbsjl89DgXBYLyOEyaCSIveIx5jibZfNBgRHLSW/At5mEZi/al1LGKN+Dit2iDtjla1nGq4hZkYTIr1ctNvYEEAcrrUR2tXAF4Lhw==
  template:
    metadata:
      creationTimestamp: null
      name: openclaw-node-secrets
      namespace: openclaw-node
    type: Opaque
