---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ggus-token
  namespace: aegis
spec:
  encryptedData:
    GGUS_TOKEN: AgBs0wbXD2W45AaAAMENR2R5LCnWLJvNaz/KmkInv77Tp7Df/vr2ztuWTFr0f/Fw7TFCCVlBxKC9/j2M5ydYLv3VVBWyJ6QfTjmO9gm9tXtxyvafUR4FmX51vy8yXG/t1K9kYjNLva0MvT1LXeqhUI+KApGCnwRR/cI7JbMO/LrcjsLR1q+gQsk3rxt5N4YxUMsRuuQC7m30NU75albQPONMOTn7AIHR8hTEWIQ2+lORHq0rfd0tRFbMjHy5vM/3gRKx5I9bl0NzAF5Jde57yrAK2jbkef3alANxjURQm1hxCX0evvSlhu95uMTNU9pF5ETbjQ6cBcxA/BLA6YPAnEsiOI47dDVquQWtYaZrGivHqexGKZzOzvEZZpjNoi8p09NuAGF72Oh352oeBAaLAqlTxDEUAOlQwGqqY0yJu6jjhSeafdstjOOAYJ7+tKCfuUL0O9lm9+vRdScjAQ91gM+KrQAsxJiwOpxe/Idst/I2mQm+uFnfZYfqlAHU26ZAHxzqdox4PrAvWFmN/oVTgaafMxCigPYj3LfZlcQRWAgv7QIkvGcY5Sx/iL7+4xR34aeL3FiSyq+IKE21EiEgrduWrrzJ4snetuXPhHNGckeRt+ZzWwqMtGuTdCBKBewNQN4FTPi1KR8MSFIq17/xl4XS6Hznvm0Y/lw1ABL37RTEnUKnuZCVoaB2gJPP6Hd5CB0yIDgA6Dm2BfnLbP1YWF0XOLyr5fvjbVXs6cRXAwBPz+td1bktTsmm4A19sknynUiFahMOTU8SfzFvBlmVuT3k
  template:
    metadata:
      creationTimestamp: null
      name: ggus-token
      namespace: aegis
    type: Opaque
