---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mcp-keys
  namespace: aegis
spec:
  encryptedData:
    API_KEY_1: AgB9NbiVqkcA3aul6xKsAbtPutbyxOLdxQvVqDJCojQ40Eq+NvrlH8cZAVuzOsKxMMnXr9DMv3HeHVpHCPNyjtJW3y2UwZ8Oh1VyvQ2qk2wdkeRVej0DWB/E3YU8rhXnpiRRvAbJuKtdb/mfhT8I/RZJ/Fsgrj5/8RX3EMCvNESP6W+1OxSTgdH3MqmdB44PjRtVqG0FxeEWHiUnxIm77YBEgEVDkBLEhzMH4M9ifeKEJxw79SukKme4kB1V5ISlH52x+zsfz0F1AeytcTXYaGTqKBWya06qOCAq3tctifZWfBWbtJ58FReArxknKvryhV2iOx4rbx8JEeAkF4d5sqNM1s4YctisoifvoLHWfz7h8cm2HcBfuUWQuqaC6zUJAWvY5hGBaOUNJWigzkLlL4hYimDcFfPBYK5DeufXKiJ58AXrOeuHCfBNb96dZRNDDwt2pK/UHS4LcyRNcSuEVmaeqrOXDOA8biAML3azZkJNMPJQyMStubstUC7es1aHlYWhorTFem/eRPE11iujIA73CuF9gCVHS1B0uj/MyyALyyXFFruNxuOq+wO1fOSQnr7uuvO5TguIUbhiHoWpk/qHGVV8W4C9r+cJU2/jILKRRKFEllDISvpqfyh7KtedDmCHaCBIxFnrDZgjIytqCtdES9zqL66Cv2a8c4W1gV6kXVTLVd69olbjotk3AQSdIddeG0L2
    API_KEY_2: AgBYihBxf/Ry6kzAvv13m7f6RU+iafeiqit/tzIJCefSNCch7sOb86yBRCM9t2QTeQj8UWsmgrL8taY9YOOTm0fX6aDuJc+OzhmWpyNJTaPgRbkFiG97mQXBRYU51qwOK1yDKgu+Aq0Z0d9Pqmlj4zpjp461ZP691q774r7cK9hgyFGrirk5f8kG0QJvXu+vOcgtnmodAgfkuYJocnBooeg1shf2TN1d072TO5UYhIyJZguHBPIq4hnGNlVY5sdrcldM3kMgPZMoHZQx/hZSqpgJ0myi3F8iQ0OmbCQE03sy2nvAZirLxTzHs/JdO4LOdm23r9fyNUs3//2OoAHA5Srf8bQMRlFW3OFTjJT5IxX2+WS0VsjtHFgSFg5MOcoVcleWUeKfag2XAIfQrHjp9pLiuMlgca5ewDVSBB0AA2NbuzX4Ow8Sv4VW2V+gsTvF+RJntM/yQiLn9PHPYNpG4o1j1j5e0hyDI+OQi3LAEru87JckQEMXCygL0GyfrR1nNcTXsNP55/CYvwXkCCN0YI45EaQ1IIhfcTjCGtDEpLtJiJe3ziiGjPuEslAaenAR3aua4uskTgrl2hi4y6fViSxA1glkqUozrFZdlQP14cvHOw890370Tg+4NJ6iPL28KIn8KYbu5VxNzf599xdwdOiMmBJ6AVllWkGBYXf6YfQiG3aA7JxDtrEmDO/rUghGaKj/Q9as37iaymLeba5SFA1oTuu9ztmhmr9VftazjRtsEes/GvZXg4saYyuXHQ==
  template:
    metadata:
      creationTimestamp: null
      name: mcp-keys
      namespace: aegis
    type: Opaque
