---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mcp
  namespace: aegis
spec:
  encryptedData:
    mcp-client: AgChkeDLbEJeP1h8pTME7zeIGTj5+9QxUyfR9RwnkA5zP+vH+pVIJsayMnHH4boqrEzj9CME2mbgQLQrDkSkZP+PB9LWtPOb2ruuE49pCx+wcVxIqsxzNc+3zFCTyOt/C+Tz89mIHiHEu8XkOeyRKbzxmXtx0qiJKylWSz9hFiS8b+gsvj+dg59LWoJIbd1JRfgeQ+X8Itx35/SHZ3KTNboGgdwGdymSbciapbQt6rx11t1pi40lW2zgcDooW0TLmhj6xXkPR2uKrcOuDWMpHHYKtQcNeSCCJwe2VNGt6wmjJbDuqJv0r9T8fFdPl6nj8OBVpauNQvTdmEXEPs2cBGGrIzVR20El/3W8ecjFkH5Vypz2spHHYKITpZP6NySWSP886GUhhDCiCzJ9BnUgPL3PTl8eJVqszdbjep7YjJCz9RlRaaOcxspYnJjmFLNkZ02HJFjnCBQtjxJMvRxvX/dhzk5ldf4xf+ZxA0WVVwkRJlXngQbW+P8rep9LtFbUr4Q9nBaa42zNeWVHFZOVw8WZnGA7EhX7ftEiYH5HQebhn/q+SNuyyDNOI5kq1QnoZjsBTOzkdrtjWU9Fizt0RyramSP7jYwo6t/6Ric2+V+7DhnpSsk+MxOaSKS6xWIv9Gd6czO1UEZa6Jrhyx5b8wZN9UTnCdHkPQU2ieORCSklkcqhNi9b2SjCASi9IA86XUt4gn9SRQaVNKx0uRwQYLliczPFNG/nutzhDc7TWyuPVw==
  template:
    metadata:
      creationTimestamp: null
      name: mcp
      namespace: aegis
    type: Opaque
